version: 0.1
phases:
  install:
    runtime-versions:
      node: nodejs10.x
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket lambda-cd-bucket-test --output-template-file deploy.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - deploy.yaml