AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-gateway-test

  Sample SAM Template for api-gateway-test
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  DomainName:
    Type: String
    Default: api.esource.roweitdev.co.uk
    Description: Domain name to call the api from.
  WildcardDomainName:
    Type: String
    Default: '*.esource.roweitdev.co.uk'
    Description: Used to provide the certificate to validate all api domains.
  HostedZoneName:
    Type: String
    Default: esource.roweitdev.co.uk.
    Description: Name of the desired hosted zone.
  HostedZoneId:
    Type: String
    Default: Z3H3DJ5LAUWBA6
    Description: Hosted zone id of the desired hosted zone.
  ApiBasePath:
    Type: String
    Default: v1
    Description: Base path of the api. 'v1' - example.co.uk/v1/endpoints

Resources:
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
  
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      EndpointConfiguration: REGIONAL
      DefinitionUri: swagger.yaml

  GetUsersLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestApi
    - GetUsersFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetUsersFunction
      Principal: apigateway.amazonaws.com

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref WildcardDomainName
      DomainValidationOptions:
        - DomainName: !Ref WildcardDomainName
          ValidationDomain: !Ref WildcardDomainName
      ValidationMethod: 'DNS'

  GatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !Ref Certificate
      DomainName: !Ref DomainName
      EndpointConfiguration:
        Types: [REGIONAL]

  APIBasePathMapping:
    DependsOn: [ServerlessRestApi]
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref GatewayDomain
      RestApiId: !Ref ServerlessRestApi
      Stage: dev
      BasePath: !Ref ApiBasePath

  APIDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt GatewayDomain.RegionalDomainName
          HostedZoneId: !GetAtt GatewayDomain.RegionalHostedZoneId